---
deployment:
  tasks:
    # 1. Deploy App Code to Production App Root
    - export APPROOT=/home/suntrans/suntransflask/
    - /bin/cp -R /home/suntrans/sunbible_git/suntransflask/* $APPROOT


    # 2. Deploy Static Files to Web Root
    - export WEBROOT=/home/suntrans/public_html/
    - /bin/cp -R /home/suntrans/sunbible_git/public_html/* $WEBROOT
